### ISSUE TITLE
SvgIcon is broken on the server

### ISSUE THREAD

**Issue by misund** [dbmedialab/shiny#1341]
SvgIcon does not render on the server.

When fixing it, we should also make sure that the SvgIcon bundle itself stays dynamic, at least on the client.

This bug is fixed when:
- [ ] The icons render both on the server and on the client
- [ ] An external react component that imports `SvgIcon` and uses it to display an icon does not have to include (on the client) the code for every single icon that exists

**Comment by NatalyMac** [comment]
well, what we have after digging 
in shiny I changed a little to clarify what is going and to show what works what does not work 
`const iconSets = {
	default: () => console.log('icon set returns default'),
	dorris: () => console.log('icon set returns dorris'),
}

class SvgIcon extends React.PureComponent {
	constructor(props) {
		super(props);
		this.state = { module: () => null };
	}
	
	componentWillMount() {
		console.log('icon svg will mount start');
		const { name, set } = this.props;
		const resolveIconSet = iconSets[set] || iconSets.default;
		console.log('resolveIconSet');
		console.log(resolveIconSet());

		import('./dorris').then((c) => {
			console.log('try to import')
			console.log(c);
			return c.default;
		}).catch(err => console.log(err))
		console.log('icon svg will mount end');
	}`

and here is result :
![Screenshot from 2019-08-02 17-51-28](https://user-images.githubusercontent.com/15108569/62379054-d0670600-b54e-11e9-9a1f-d8393cbc7989.png)
![Screenshot from 2019-08-02 17-51-11](https://user-images.githubusercontent.com/15108569/62379057-d0670600-b54e-11e9-88ea-23e59854ec49.png)
