### ISSUE TITLE
DX: make html and component  more understandable

### ISSUE THREAD

**Issue by SindreSvendby** [dbmedialab/shiny#375]
(DX -> developer experience)

It can be hard to find the correct component if your are not familiar with the project and just jump into the react debugger or the html code since we are using styled-components and all class names are autogenerated. 

This is indeed a issue we should fix, but it's also impotent to remember that we want to work with components primarily trough shiny or storybook, and not on a page. this is a new habit that we need to learn.

**Comment by SindreSvendby** [comment]
How it looks before the fix
![oppskrifer-footer-before](https://user-images.githubusercontent.com/1047421/38511619-fc8f6d6c-3c28-11e8-8f0a-134726f5306f.png)

After:
![oppskrifer-footer-after](https://user-images.githubusercontent.com/1047421/38511636-0ec0c530-3c29-11e8-840a-c496541db990.png)

**Comment by misund** [comment]
@SindreSvendby Could you link to the fix from here, please?

**Comment by SindreSvendby** [comment]
I did something wrong here, github did not pick this up, will readup on my github skillz :+1: 
https://github.com/dbmedialab/shiny/pull/376 is the PR related to this issue!

**Comment by Fumler** [comment]
We actually had this in before, don't remember why we removed it xD
