### ISSUE TITLE
LazyProgressiveImage reloads on rerender

### ISSUE THREAD

**Issue by misund** [dbmedialab/shiny#384]
When paginating components that contain a LazyProgressiveImage, the image will reload everytime. See if we can avoid this with a shouldComponentUpdate() function on LazyProgressiveImage.

Temporary workaround: Use shouldComponentUpdate = () => false on the paginated component

**Comment by tnlitv** [comment]
Tried to make it with 
```
	shouldComponentUpdate(nextProps, nextState) {
		return false;
	}
```
and 
```
	shouldComponentUpdate(nextProps, nextState) {
		return !this.state.isLoaded;
	}
```
but none of those worked. :(
Gonna research later.

**Comment by misund** [comment]
Is this still an issue @Fumler ?

**Comment by Fumler** [comment]
No idea.
