### ISSUE TITLE
ci: Add stable node to travis testing

### ISSUE THREAD

**Issue by misund** [dbmedialab/shiny#415]
Stable was removed when node v10 was released, because an indirect dependency specifically did not support >10.

When our dependency graph has updated to address this issue, we should add stable node back in to our tests.

See #414 
See anodynos/upath#14
See anodynos/upath#15

**Comment by anodynos** [comment]
Hello everyone - I merged [anodynos/upath#15](https://github.com/anodynos/upath/pull/15) & published it  - thanks & sorry for the delay! You can close the issue, once you check its working.
