### ISSUE TITLE
De-bloat TrysilPlug

### ISSUE THREAD

**Issue by misund** [dbmedialab/shiny#879]
[The `SvgIcon` import in `TrysilPlug`](https://github.com/dbmedialab/shiny/blob/d666d4ca656b336dcd722977533beb68122c2c6b/src/molecules/TrysilPlug.js) bloats webpack chunks that include TrysilPlug significantly, but the icon component is only used when the `displayIcon` prop is true.

Is it possible to make it a dynamic import without binding ourselves to next?

See also #880

**Comment by misund** [comment]
One solution could be to create a lighter-weight `PlayIcon`.

**Comment by Fumler** [comment]
Could try just using the "native" dynamic `import()` in shiny and see if that helps in wolverine-frontend?

**Comment by misund** [comment]
yeah, I was thinking nested in a delta function, like
`() => import()`
